#!/usr/bin/env python3

import argparse
import re
import collections
import more_itertools

def indices(input_list, val):
    ''' Returns list of indices at which "val" occurs within "input_list" '''
    return list(more_itertools.locate(input_list, pred=lambda x: x==val))

def isolate_dupes(commandlist, verbose=True):
    ''' Returns list with duplicate definitions commented out.
        "commandlist" is of the form [commandtype, commandname, line_of_code].
        Output is the same as the input, except that the duplicates are moved to right 
        after the first occurence, with order otherwise conserved.
    '''
    # List of command names
    names = [el[1] for el in commandlist]
    # Dictionnary giving frequency of each name
    counter = collections.Counter(names)
    
    # List for outputting the commands
    outputlist = []
    
    # Iterate over the distinct keys
    for key in counter:
        # Get the indices at which "key" occurs in the list of names
        idxs = indices(names, key)
        
        assert len(idxs)==counter[key] # Consistency check
        
        for i, idx in enumerate(idxs):
            if i==0: # Add the first occurence as is
                outputlist.append( commandlist[idx] )
                # Print duplicate commands
                if verbose and len(idxs)>1: print('\t{}'.format(commandlist[idx]))
            else: # Add further occurences as comments
                commandtemp = commandlist[idx]
                # Print duplicate commands
                if verbose and len(idxs)>1: print('\t{}'.format(commandtemp))
                commandtemp[2] = r'% ' + commandtemp[2]
                outputlist.append( commandtemp )
        if verbose and len(idxs)>1: print()
    
    return outputlist


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.prog = "merge.py"
    parser.description = 'Merge LaTex macro files ("newcommand" and "renewcommand" only). See README.md for details.'
    
    parser.add_argument("inputfile", help="Input file", nargs='+', type=str)
    parser.add_argument("-o", "--outputname", help="Name for output", required=True, type=str)
    parser.add_argument("-v", "--verbose", help="Show merged macros", action="store_true")
    args = parser.parse_args()
    
    if args.verbose:
        print()
        print('inputfile = {}'.format(args.inputfile))
        print('outputname = {}'.format(args.outputname))
        print()
    
    # List for holding commands
    newcommands = []
    renewcommands = []
    
    # Regular expressions for matching
    com1_re = r'(\\newcommand)'
    com2_re = r'(\\renewcommand)'
    name_re = r'[ {]*(\\[^ \[\]{}\\]*)'
    
    p1 = re.compile(com1_re + name_re) # Matches "newcommand" definitions
    p2 = re.compile(com2_re + name_re) # Matches "renewcommand" definitions
    
    # Open files and collect command definitions
    for filename in args.inputfile:
        with open(filename, 'r') as fh:
            all_lines = fh.readlines()
        
        for line in all_lines:
            # "match" only matches the expression if it is at the start of "line"
            m1 = p1.match(line) # Search for "newcommand" definitions
            m2 = p2.match(line) # Search for "renewcommand" definitions
            
            # Strip trailing whitespaces (including newlines) and add file of origin
            line = line.rstrip() + '\t% ' + filename
        
            if m1 is not None:
                assert m2 is None # Consistency check
                newcommands.append( [m1.group(1), m1.group(2), line] ) # Append to list
        
            if m2 is not None:
                assert m1 is None # Consistency check
                renewcommands.append( [m2.group(1), m2.group(2), line] ) # Append to list
    
    # Make lists with duplicates commented out
    if args.verbose: print('Duplicate "newcommand" definitions:\n')
    newcommands_nodupes   = isolate_dupes(newcommands, verbose=args.verbose)
    if args.verbose: print('Duplicate "renewcommand" definitions:\n')
    renewcommands_nodupes = isolate_dupes(renewcommands, verbose=args.verbose)
    
    # Write to file
    with open(args.outputname, 'w') as fo:
            fo.write('\n')
            for newcommand in newcommands_nodupes:
                fo.write(newcommand[2] + '\n')
            fo.write('\n')
            for renewcommand in renewcommands_nodupes:
                fo.write(renewcommand[2] + '\n')
